In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

In [3]:
data_path=Path(r'C:\Users\vinee\ML_Project\data\raw\electricity_consumption_raw.csv')
df=pd.read_csv(data_path)
print('shape',df.shape)
df.head()

shape (42372, 1036)

,1/1/2014,1/2/2014,1/3/2014,1/4/2014,1/5/2014,1/6/2014,1/7/2014,1/8/2014,1/9/2014,1/10/2014,...,10/24/2016,10/25/2016,10/26/2016,10/27/2016,10/28/2016,10/29/2016,10/30/2016,10/31/2016,CONS_NO,FLAG
0,0.0,0.0,0.01,0.0,0.0,0.00,0.00,0.00,0.00,0.00,...,0.02,0.06,0.58,0.89,0.35,0.38,0.70,0.25,0387DD8A07E07FDA6271170F86AD9151,1
1,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,...,17.13,14.32,16.37,26.33,19.06,17.38,13.94,14.14,01D6177B5D4FFE0CABA9EF17DAFC2B84,1
2,0.0,0.0,0.00,0.0,0.0,4.98,9.87,11.29,13.44,11.34,...,NaN,1.43,2.22,2.41,3.48,2.89,1.88,1.16,4B75AC4F2D8434CFF62DB64D0BB43103,1
3,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,...,20.98,18.47,15.50,14.80,19.28,16.10,17.51,16.67,B32AC8CC6D5D805AC053557AB05F5343,1
4,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,...,0.61,1.33,0.55,1.62,1.53,2.10,1.16,2.13,EDFC78B07BA2908B3395C4EB2304665E,1

In [67]:
print('no. of comlumns',len(df.columns))
print('\nFirst 5 comuns')
print(df.columns[:5].tolist())
print('\nlast 5 columns')
print(df.columns[-5:].tolist())

no. of comlumns 1036

First 5 comuns
['1/1/2014', '1/2/2014', '1/3/2014', '1/4/2014', '1/5/2014']

last 5 columns
['10/29/2016', '10/30/2016', '10/31/2016', 'CONS_NO', 'FLAG']

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42372 entries, 0 to 42371
Columns: 1036 entries, 1/1/2014 to FLAG
dtypes: float64(1034), int64(1), object(1)
memory usage: 334.9+ MB

In [28]:
df.dtypes.value_counts()

float64    1034
object        1
int64         1
Name: count, dtype: int64

In [29]:
df['FLAG'].value_counts(dropna=False)

FLAG
0    38757
1     3615
Name: count, dtype: int64

In [30]:
print('total rows',len(df))
print('total colums',len(df.columns))
print('duplicates',df['CONS_NO'].duplicated().sum())

total rows 42372
total colums 1036
duplicates 0

In [31]:
miss_sum=df.isnull().sum()
print('total missing cells=',miss_sum.sum())
print('colums with missing values',(miss_sum>0).sum())
miss_sum.sort_values(ascending=False).head(10)

total missing cells= 11233528
colums with missing values 1034

10/3/2014    42357
3/19/2014    21505
2/28/2014    20985
3/4/2014     20820
3/3/2014     20806
4/19/2014    20633
2/20/2014    20536
2/23/2014    20494
2/24/2014    20326
3/2/2014     20224
dtype: int64

### consumer wise missing values

In [32]:
consumer_miss=df.drop(columns=['CONS_NO','FLAG']).isnull().sum(axis=1)
consumer_miss.describe()

count    42372.000000
mean       265.116775
std        298.059056
min          1.000000
25%         13.000000
50%        110.000000
75%        641.250000
max       1034.000000
dtype: float64

### Date Columns identify

In [33]:
meta_col = ['CONS_NO','FLAG']
date_col = [col for col in df.columns if col not in meta_col]
print('date columns=',len(date_col))
print('first date=',date_col[0])
print('last date=',date_col[-1])

date columns= 1034
first date= 1/1/2014
last date= 10/31/2016

In [68]:
date=pd.to_datetime(date_col,format='%m/%d/%Y')
print('minimun date=',date.min())
print('maximun date=',date.max())
print('Expected date count=',len(pd.date_range(date.min(),date.max(),freq='d')))
print('Actual date count=',len(date))

minimun date= 2014-01-01 00:00:00
maximun date= 2016-10-31 00:00:00
Expected date count= 1035
Actual date count= 1034

#### Consumption

In [49]:
consumption_data = df[date_col]
consumption_data.describe()

,1/1/2014,1/2/2014,1/3/2014,1/4/2014,1/5/2014,1/6/2014,1/7/2014,1/8/2014,1/9/2014,1/10/2014,...,10/22/2016,10/23/2016,10/24/2016,10/25/2016,10/26/2016,10/27/2016,10/28/2016,10/29/2016,10/30/2016,10/31/2016
count,25870.000000,25873.000000,25872.000000,25874.000000,25874.000000,25878.000000,25879.000000,25907.000000,25907.000000,25912.000000,...,41846.000000,41824.000000,41820.000000,41665.000000,41623.000000,41397.000000,41443.000000,41637.000000,41634.000000,41569.000000
mean,7.168735,7.057237,6.704972,7.237638,7.394550,6.939544,7.271432,6.862706,6.956579,6.954202,...,9.555905,9.692272,8.503682,9.032455,9.396710,9.878270,9.934374,8.845107,8.355138,8.224294
std,34.131237,30.086443,31.223720,49.508191,41.464202,37.583286,64.114745,34.842458,39.684055,40.017856,...,77.527527,75.590148,81.278000,79.378526,80.896258,92.312243,88.382736,84.201505,78.702362,70.861576
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.790000,0.810000,0.750000,0.790000,0.810000,0.840000,0.870000,0.790000,0.770000,0.770000
50%,3.310000,3.400000,3.110000,3.340000,3.560000,3.325000,3.120000,3.210000,3.120000,2.870000,...,4.640000,4.780000,4.290000,4.420000,4.530000,4.650000,4.710000,4.450000,4.390000,4.290000
75%,8.910000,8.570000,8.110000,8.320000,8.880000,8.290000,8.090000,8.120000,8.210000,8.170000,...,9.370000,9.662500,8.400000,8.680000,9.010000,9.350000,9.510000,8.750000,8.490000,8.110000
max,3318.000000,2500.000000,2674.000000,5670.000000,4854.000000,4170.000000,7119.810000,3546.000000,4416.000000,3966.000000,...,11370.000000,11100.000000,13560.000000,11940.000000,12480.000000,15180.000000,14970.000000,14100.000000,12480.000000,9990.000000

In [55]:
print('Minimum',consumption_data.min().min())
print('Maximum',consumption_data.max().max())
print('Median',consumption_data.stack().median())
print('Mean',consumption_data.stack().mean())

Minimum 0.0
Maximum 800003.32
Median 4.59
Mean 9.258860091423587

#### Zero Consumption

In [59]:
zero_cons=(consumption_data==0).sum().sum()
total_values=consumption_data.size
print('zero readings',zero_cons)
print('zero count percentage',abs(zero_cons/total_values)*100)

zero readings 5788603
zero count percentage 13.212173343186196

#### Flag Distribution

In [69]:
flg_dis=(df['FLAG'].value_counts().rename_axis('FLAG').reset_index(name='Consumer'))
flg_dis['Percentage']=((flg_dis['Consumer']/flg_dis['Consumer'].sum())*100)
flg_dis

   FLAG  Consumer  Percentage
0     0     38757   91.468423
1     1      3615    8.531577